---

  - name: Create new network subnet named Data
    purefb_subnet:
      name: "Data"
      prefix: "{{ data_network.prefix }}"
      gateway: "{{ data_network.gateway }}"
      mtu: "{{ data_network.mtu }}"
      vlan: "{{ data_network.vlan }}"
      state: present
      fb_url: "{{ url }}"
      api_token: "{{ api }}"


  - name: Create new network interfaces
    purefb_network:
      name: "data1"
      address: "{{ interface.address }}"
      state: present
      fb_url: "{{ url }}"
      api_token: "{{ api }}"
    loop: "{{ data_network['interfaces'] }}"
    loop_control:
      loop_var: interface