---
  - name: Pure FlashBlade Settings Configuration
    include_tasks:
      file: all.yml
    vars:
      name: "{{ item.name }}"
      url: "{{ item.fb_url }}"
      api: "{{ item.api_token }}"
      ds_uri: "{{ item.ds_uri }}"
      data_network: "{{ item.data_network }}"
    loop: "{{ target_arrays }}"
