- name: Gather Fb info
  hosts: localhost
  tasks:
    - name: collect all FlashBlade Configuration info
      purestorage.flashblade.purefb_info:
        gather_subset:
          - all
        fb_url: 172.29.10.190
        api_token: T-d5064a2c-45ed-4c70-9a3d-7cc6dc991e83
      register: blade_info

    - name: Show all flashblade info
      debug:
        msg: "{{ blade_info }}"

