---
- name: Execute command as ir user
  hosts: localhost
  tasks:
    - name: Execute command
      execute_ir_commandline:
        password: pureuser
        command: 'ls -l /usr'
        fb_url: 172.29.10.190
      register: command_output

    - name: Show the output
      debug:
        msg: "{{ command_output }}"
