---
  - name: Get facts for {{ name }}
    purestorage.flashblade.purefb_info:
      gather_subset:
        - config
      fb_url: "{{ url }}"
      api_token: "{{ api }}"
    register: blade_facts

  - set_fact:
      blade_syslog_servers: "{{ blade_facts['purefb_info']['config']['syslog'] }}"

  - name: Remove syslog servers not matching template settings for {{ name }}
    purestorage.flashblade.purefb_syslog:
      name: "{{ syslog.name }}"
      state: absent
      fb_url: "{{ url }}"
      api_token: "{{ api }}"
    when: slog.syslog_servers | selectattr('name','equalto', syslog.name) | list | count == 0
    loop: "{{ blade_syslog_servers }}"
    loop_control:
      loop_var: syslog

  - name: Add syslog missing servers from template for {{ name }}
    purestorage.flashblade.purefb_syslog:
      name: "{{ syslog.name }}"
      address: "{{ syslog.address }}"
      protocol: "{{ syslog.protocol }}"
      fb_url: "{{ url }}"
      api_token: "{{ api }}"
    when: blade_syslog_servers| selectattr('name','equalto', syslog.name) | list | count == 0
    loop: "{{ slog.syslog_servers }}"
    loop_control:
      loop_var: syslog

