---

- name: Load Target Flashblade Info into Global Variables
  load_array_vars:
    site: "{{ site_env | default(False) }}"
    flashblade: "{{ site_blade | default(False) }}"
  register: array_vars

- set_fact:
    target_arrays: "{{ array_vars['target_arrays'] }}"
    site_env: "{{ array_vars['site_env'] }}"

# Read the appropriate variables file for site_env variable passed
- include_vars: ./roles/copy-template/files/npc_vars.yml
  when: site_env == 'npc'

- include_vars: ./roles/copy-template/files/wpc_vars.yml
  when: site_env == 'wpc'

- name: Copy in site variables and include them
  template:
    src: vars_file_template.yml
    dest: ./vars/vars_file.yml

# Set all the vars in the template we just created
- include_vars:
    file: ./vars/vars_file.yml

