---
  - name: Get facts for {{ url }}
    purefb_info:
      gather_subset: config
      fb_url: "{{ url }}"
      api_token: "{{ api }}"
    register: array_facts

  - set_fact:
      array_base_dn: "{{ array_facts.purefb_info.config.smb_directory_service.base_dn }}"
      array_bind_user: "{{ array_facts.purefb_info.config.smb_directory_service.bind_user }}"

  - name: Debug output
    debug:
      msg: "{{ array_facts }}"

  # Delete Current Directory Service config if base_dn or bind_user of the current settings do not match standard
  - name: Clear Directory Services configuration for {{ url }}
    purefb_ds:
      state: absent
      fb_url: "{{ url }}"
      api_token: "{{ api }}"
    when: (array_base_dn != ds.base_dn) or
          (array_bind_user != ds.bind_user)

  # Create or recreate Directory Service config
  - name: Configure Directory Services for {{ name }}
    purestorage.flashblade.purefb_ds:
      enable: true
      dstype: "{{ ds.dstype }}"
      uri: "{{ ds.ds_uri }}"
      base_dn: "{{ ds.base_dn }}"
      bind_user: "{{ ds.bind_user }}"
      bind_password: "{{ ds.bind_password }}"
      fb_url: "{{ url }}"
      api_token: "{{ api }}"
