---
# handlers file for purearray
- name: Email Result
  mail:
    host: "{{ mail_relay_host }}"
    port: 25
    to: "{{ email_notify_user }}"
    subject: Pure Syslog configuation changed
    body: "Pure System Syslog configuration changed"
